version: '3'

tasks:
  build-version:
    cmds:
      - git-conventional-commits version > settings/version.txt || echo 'not installed git-conventional-commits' > settings/version.txt
  build:
    cmds:
      - task: build-version
      - mkdir -p dist
      - rm dist/* | true
      - GOOS=windows GOARCH=amd64 go build -v -o dist/darktool-windows-amd64.exe main.go
      - GOOS=linux GOARCH=amd64 go build -v -o dist/darktool-linux-amd64 main.go
  run:
    cmds:
      - go run .

  cobra-cli-get:
    cmds:
      - go install github.com/spf13/cobra-cli@latest

  test:
    cmds:
      - mkdir -p tools/randline/tests/temp
      - DARKTOOL_FREELANCER_FOLDER={{.PWD}} go test ./... {{.CLI_ARGS}}
    vars:
      PWD:
        sh: echo '$(pwd)'

  doc-web:
    cmds:
      - godoc -http=:6060

  setup-ln:
    cmds:
      - ln -s {{.PWD}}/dist/darktool-linux-amd64 {{.PWD}}/../Discovery-DEV-Groshyr/darktool || true
      - ln -s {{.PWD}}/dist/darktool-linux-amd64 {{.PWD}}/../Discovery-Freelancer-Reimagined/darktool || true
      - ln -s {{.PWD}}/../Discovery-DEV-Groshyr {{.PWD}}/Discovery-DEV-Groshyr || true
      - ln -s {{.PWD}}/dist/darktool-linux-amd64 {{.PWD}}/darktool
    vars:
      PWD:
        sh: echo '$(pwd)'

