version: '3'

tasks:
  build:
    cmds:
      - mkdir -p dist
      - rm dist/* | true
      - GOOS=windows GOARCH=amd64 go build -v -o dist/darktool-windows-amd64.exe main.go
      - GOOS=linux GOARCH=amd64 go build -v -o dist/darktool-linux-amd64 main.go

  run:
    cmds:
      - go run .

  cobra-cli-get:
    cmds:
      - go install github.com/spf13/cobra-cli@latest

  test:
    cmds:
      - mkdir -p tools/randline/tests/temp
      - go test ./... -v

  doc-web:
    cmds:
      - godoc -http=:6060
