version: '3'

tasks:
  tag:
    cmds:
      - git tag v{{.TAG}}
    vars:
      TAG:
        sh: git-conventional-commits version

  tag-push:
    cmds:
      - git push origin v{{.TAG}}
    vars:
      TAG:
        sh: git-conventional-commits version

  deploy:
    cmds:
      - task: tag
      - task: tag-push

  version:
    cmds:
      - git-conventional-commits version

  build-version:
    cmds:
      - autogit semver > settings/version.txt || echo 'not installed autogit' > settings/version.txt
  build:
    cmds:
      - task: build-version
      - mkdir -p dist
      - rm dist/* | true
      - GOOS=windows GOARCH=amd64 go build -v -o dist/fldarklint-windows-amd64.exe main.go
      - GOOS=linux GOARCH=amd64 go build -v -o dist/fldarklint-linux-amd64 main.go
  run:
    cmds:
      - go run .

  cobra-cli-get:
    cmds:
      - go install github.com/spf13/cobra-cli@latest

  test:
    cmds:
      - mkdir -p tools/randline/tests/temp
      - DARKTOOL_FREELANCER_FOLDER={{.PWD}} go test ./... {{.CLI_ARGS}}
    vars:
      PWD:
        sh: echo '$(pwd)'

  doc-web:
    cmds:
      - godoc -http=:6060

  changelog:
    cmds:
      - git-conventional-commits changelog {{.CLI_ARGS}}

  setup-prod:
    cmds:
      - sudo ln -s {{.PWD}}/dist/fldarklint-linux-amd64 /usr/local/bin/fldarklint
    vars:
      PWD:
        sh: echo '$(pwd)'

  setup-dev:
    cmds:
      - sudo rm /usr/local/bin/fldarklint | true
      - echo -e '#!/bin/bash\nset -x\nfilepath=`pwd`\ncd /home/naa/repos/pet_projects/darklab_fldarklint && FLDARKLINT_PROJECT_FOLDER=$filepath go run . $@' | sudo tee /usr/local/bin/fldarklint
      - sudo chmod 777 /usr/local/bin/fldarklint
    vars:
      PWD:
        sh: echo '$(pwd)'

