# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Install Task
      run: |
        sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - uses: actions/checkout@v4
      with:
        repository: 'darklab8/fl-data'
        path: '${{ github.workspace }}/fl-data'
        token: ${{ secrets.FL_DATA_KEY }}

    - run: ls ./fl-data

    - name: Build
      run: task build

    - name: Test
      run: task test -- -v
      env:
        DARKLINT_LOG_LEVEL: "DEBUG"
        DARKLINT_FREELANCER_FOLDER: ${{ github.workspace }}/fl-data
